#include "AllPokemon.h"
#include <iostream>

enum PokemonType {
    Bug,
    Dragon,
    Electric,
    Flying,
    Fire,
    Ghost,
    Grass,
    Ground,
    Ice,
    Normal,
    Poison,
    Psychic,
    Rock,
    Steel,
    Water,
    None
};

struct PokemonMove {
    std::string MoveName;
    PokemonType MoveType;
    PokemonMovePhysOrSp PhysOrSp;
    int Power;
};


 struct Pokemon{
    std::string Name;
    PokemonType Type1;
    PokemonType Type2;
    int MaxHP;
    int CurrentHP;
    int ATK;
    int DEF;
    int SpATK;
    int SpDEF;
    int Speed;
    int Level;
    std::string FrontSprite;
    std::string BackSprite;
    PokemonMove Moveset[4];
 };



 Pokemon* allPokemon(){
            Pokemon ListOfPokemon[30];
            ListOfPokemon[0] = definePokemon("Pidgeot",
                                                Normal,
                                                Flying,
                                                83,
                                                83,
                                                80,
                                                75,
                                                70,
                                                70,
                                                101,
                                                "Pidgeot_Front.png",
                                                "Pidgeot_Back.png",
                                                "Aerial Ace",
                                                Flying,
                                                Physical,
                                                60,
                                                "Steel Wing",
                                                Steel,
                                                Physical,
                                                70,
                                                "Wing Attack",
                                                Flying,
                                                Physical,
                                                60,
                                                "Gust",
                                                Flying,
                                                Special,
                                                40);

            ListOfPokemon[1] = definePokemon("Dragonite",
                                                Flying,
                                                Dragon,
                                                91,
                                                91,
                                                134,
                                                95,
                                                100,
                                                100,
                                                80,
                                                "Dragonite_Front.png",
                                                "Dragonite_Back.png",
                                                "Outrage",
                                                Dragon,
                                                Physical,
                                                120,
                                                "Wing Attack",
                                                Flying,
                                                Physical,
                                                60,
                                                "Hyper Beam",
                                                Normal,
                                                Special,
                                                150,
                                                "Flamethrower",
                                                Fire,
                                                Special,
                                                90);

            ListOfPokemon[2] = definePokemon("Aerodactyl",
                                                Flying,
                                                Rock,
                                                80,
                                                80,
                                                105,
                                                65,
                                                60,
                                                75,
                                                130,
                                                "Aerodactyl_Front.png",
                                                "Aerodactyl_Back.png",
                                                "Fire Blast",
                                                Fire,
                                                Special,
                                                110,
                                                "Aerial Ace",
                                                Flying,
                                                Physical,
                                                60,
                                                "Earthquake",
                                                Ground,
                                                Physical,
                                                100,
                                                "Wing Attack",
                                                Flying,
                                                Physical,
                                                60);

            ListOfPokemon[3] = definePokemon("Arbok",
                                                Poison,
                                                None,
                                                60,
                                                60,
                                                95,
                                                69,
                                                65,
                                                79,
                                                80,
                                                "Arbok_Front.png",
                                                "Arbok_Back.png",
                                                "Acid",
                                                Poison,
                                                Special,
                                                40,
                                                "Sludge Bomb",
                                                Poison,
                                                Special,
                                                90,
                                                "Iron Tail",
                                                Steel,
                                                Physical,
                                                100,
                                                "Earthquake",
                                                Ground,
                                                Physical,
                                                100);

            ListOfPokemon[4] = definePokemon("Gengar",
                                                Poison,
                                                Ghost,
                                                60,
                                                60,
                                                65,
                                                60,
                                                130,
                                                75,
                                                110,
                                                "Gengar_Front.png",
                                                "Gengar_Back.png",
                                                "Thunderbolt",
                                                Electric,
                                                Special,
                                                90,
                                                "Shadow Ball",
                                                Ghost,
                                                Special,
                                                80,
                                                "Psychic",
                                                Psychic,
                                                Special,
                                                90,
                                                "Shadow Punch",
                                                Ghost,
                                                Physical,
                                                60);

            ListOfPokemon[5] = definePokemon("Weezing",
                                                Poison,
                                                None,
                                                65,
                                                65,
                                                90,
                                                120,
                                                85,
                                                70,
                                                60,
                                                "Weezing_Front.png",
                                                "Weezing_Back.png",
                                                "Sludge Bomb",
                                                Poison,
                                                Special,
                                                90,
                                                "Shadow Ball",
                                                Ghost,
                                                Special,
                                                80,
                                                "Thunderbolt",
                                                Electric,
                                                Special,
                                                90,
                                                "Sludge",
                                                Poison,
                                                Special,
                                                65);

            ListOfPokemon[6] = definePokemon("Sandslash",
                                                Ground,
                                                None,
                                                75,
                                                75,
                                                100,
                                                110,
                                                45,
                                                55,
                                                65,
                                                "Sandslash_Front.png",
                                                "Sandslash_Back.png",
                                                "Slash",
                                                Normal,
                                                Physical,
                                                70,
                                                "Earthquake",
                                                Ground,
                                                Physical,
                                                100,
                                                "Strength",
                                                Normal,
                                                Physical,
                                                80,
                                                "Iron Tail",
                                                Steel,
                                                Physical,
                                                100);

            ListOfPokemon[7] = definePokemon("Marowak",
                                                Ground,
                                                None,
                                                60,
                                                60,
                                                80,
                                                110,
                                                50,
                                                80,
                                                45,
                                                "Marowak_Front.png",
                                                "Marowak_Back.png",
                                                "Double Edge",
                                                Normal,
                                                Physical,
                                                120,
                                                "Bonemerang",
                                                Ground,
                                                Physical,
                                                50,
                                                "Strength",
                                                Normal,
                                                Physical,
                                                80,
                                                "Iron Tail",
                                                Steel,
                                                Physical,
                                                100);

            ListOfPokemon[8] = definePokemon("Dugtrio",
                                                Ground,
                                                None,
                                                35,
                                                35,
                                                100,
                                                50,
                                                50,
                                                70,
                                                120,
                                                "Dugtrio_Front.png",
                                                "Dugtrio_Back.png",
                                                "Earthquake",
                                                Ground,
                                                Physical,
                                                40,
                                                "Mud-Slap",
                                                Ground,
                                                Physical,
                                                20,
                                                "Scratch",
                                                Normal,
                                                Physical,
                                                40,
                                                "Slash",
                                                Normal,
                                                Physical,
                                                70);

            ListOfPokemon[9] = definePokemon("Onix",
                                                Rock,
                                                None,
                                                35,
                                                35,
                                                45,
                                                160,
                                                30,
                                                45,
                                                70,
                                                "Onix_Front.png",
                                                "Onix_Back.png",
                                                "Double Edge",
                                                Normal,
                                                Physical,
                                                120,
                                                "Iron Tail",
                                                Steel,
                                                Physical,
                                                100,
                                                "Rock Slide",
                                                Rock,
                                                Physical,
                                                75,
                                                "Earthquake",
                                                Ground,
                                                Physical,
                                                40);

            ListOfPokemon[10] = definePokemon("Golem",
                                                Rock,
                                                Ground,
                                                80,
                                                80,
                                                120,
                                                130,
                                                55,
                                                65,
                                                45,
                                                "Golem_Front.png",
                                                "Golem_Back.png",
                                                "Rock Throw",
                                                Rock,
                                                Physical,
                                                50,
                                                "Rock Slide",
                                                Rock,
                                                Physical,
                                                75,
                                                "Earthquake",
                                                Ground,
                                                Physical,
                                                100,
                                                "Double Edge",
                                                Normal,
                                                Physical,
                                                120);

            ListOfPokemon[11] = definePokemon("Rhydon",
                                                Rock,
                                                Ground,
                                                105,
                                                105,
                                                130,
                                                120,
                                                45,
                                                45,
                                                40,
                                                "Rhydon_Front.png",
                                                "Rhydon_Back.png",
                                                "Megahorn",
                                                Bug,
                                                Physical,
                                                50,
                                                "Rock Slide",
                                                Rock,
                                                Physical,
                                                75,
                                                "Earthquake",
                                                Ground,
                                                Physical,
                                                100,
                                                "Double Edge",
                                                Normal,
                                                Physical,
                                                120);

            ListOfPokemon[12] = definePokemon("Butterfree",
                                                Bug,
                                                Flying,
                                                60,
                                                60,
                                                45,
                                                50,
                                                90,
                                                80,
                                                70,
                                                "Butterfree_Front.png",
                                                "Butterfree_Back.png",
                                                "Silver Wind",
                                                Bug,
                                                Special,
                                                60,
                                                "Psybeam",
                                                Psychic,
                                                Special,
                                                65,
                                                "Gust",
                                                Flying,
                                                Special,
                                                40,
                                                "Aerial Ace",
                                                Flying,
                                                Physical,
                                                60);

            ListOfPokemon[13] = definePokemon("Beedrill",
                                                Bug,
                                                Poison,
                                                65,
                                                65,
                                                90,
                                                40,
                                                45,
                                                80,
                                                75,
                                                "Beedrill_Front.png",
                                                "Beedrill_Back.png",
                                                "Twinneedle",
                                                Bug,
                                                Physical,
                                                25,
                                                "Solar Beam",
                                                Grass,
                                                Special,
                                                120,
                                                "Pin Missle",
                                                Bug,
                                                Physical,
                                                25,
                                                "Cut",
                                                Normal,
                                                Physical,
                                                50);

            ListOfPokemon[14] = definePokemon("Pinsir",
                                                Bug,
                                                None,
                                                65,
                                                65,
                                                125,
                                                100,
                                                55,
                                                70,
                                                85,
                                                "Pinsir_Front.png",
                                                "Pinsir_Back.png",
                                                "Cut",
                                                Normal,
                                                Physical,
                                                50,
                                                "Strength",
                                                Normal,
                                                Physical,
                                                80,
                                                "X-Scissor",
                                                Bug,
                                                Physical,
                                                80,
                                                "Bug Bite",
                                                Bug,
                                                Physical,
                                                60);

            ListOfPokemon[15] = definePokemon("Charizard",
                                                Fire,
                                                Flying,
                                                78,
                                                78,
                                                84,
                                                76,
                                                109,
                                                85,
                                                100,
                                                "Charizard_Front.png",
                                                "Charizard_Back.png",
                                                "Fire Blast",
                                                Fire,
                                                Special,
                                                110,
                                                "Dragon Claw",
                                                Dragon,
                                                Physical,
                                                80,
                                                "Aerial Ace",
                                                Flying,
                                                Physical,
                                                60,
                                                "Earthquake",
                                                Ground,
                                                Physical,
                                                100);

            ListOfPokemon[16] = definePokemon("Ninetails",
                                                Fire,
                                                None,
                                                73,
                                                73,
                                                76,
                                                75,
                                                81,
                                                100,
                                                100,
                                                100,
                                                "Ninetails_Front.png",
                                                "Ninetails_Back.png",
                                                "Flamethrower",
                                                Fire,
                                                Special,
                                                90,
                                                "Heat Wave",
                                                Fire,
                                                Special,
                                                95,
                                                "Fire Blast",
                                                Fire,
                                                Special,
                                                110,
                                                "Quick Attack",
                                                Normal,
                                                Special,
                                                40);

            ListOfPokemon[17] = definePokemon("Arcanine",
                                                Fire,
                                                None,
                                                90,
                                                90,
                                                110,
                                                80,
                                                100,
                                                80,
                                                95,
                                                "Arcanine_Front.png",
                                                "Arcanine_Back.png",
                                                "Extremespeed",
                                                Normal,
                                                Physical,
                                                80,
                                                "Overheat",
                                                Fire,
                                                Special,
                                                130,
                                                "Aerial Ace",
                                                Flying,
                                                Physical,
                                                60,
                                                "Iron Tail",
                                                Steel,
                                                Physical,
                                                100);

            ListOfPokemon[18] = ("Blastoise",
                                                Water,
                                                None,
                                                79,
                                                79,
                                                83,
                                                100,
                                                85,
                                                105,
                                                78,
                                                "Blastoise_Front.png",
                                                "Blastoise_Back.png",
                                                "Hydro Pump",
                                                Water,
                                                Special,
                                                110,
                                                "Ice Beam",
                                                Ice,
                                                Special,
                                                90,
                                                "Earthquake",
                                                Ground,
                                                Physical,
                                                100,
                                                "Skull Bash",
                                                Normal,
                                                Physical,
                                                130);

            ListOfPokemon[19] = definePokemon("Gyarados",
                                                Water,
                                                None,
                                                95,
                                                95,
                                                125,
                                                79,
                                                60,
                                                100,
                                                81,
                                                "Gyarados_Front.png",
                                                "Gyarados_Back.png",
                                                "Hydro Pump",
                                                Water,
                                                Special,
                                                110,
                                                "Earthquake",
                                                Ground,
                                                Physical,
                                                100,
                                                "Hyper Beam",
                                                Normal,
                                                Special,
                                                150,
                                                "Waterfall",
                                                Water,
                                                Physical,
                                                80);

            ListOfPokemon[20] = definePokemon("Vaporeon",
                                                Water,
                                                None,
                                                130,
                                                130,
                                                65,
                                                60,
                                                110,
                                                95,
                                                65,
                                                "Vaporeon_Front.png",
                                                "Vaporeon_Back.png",
                                                "Water Pulse",
                                                Water,
                                                Special,
                                                60,
                                                "Quick Attack",
                                                Normal,
                                                Special,
                                                40,
                                                "Aurora Beam",
                                                Ice,
                                                Special,
                                                65,
                                                "Hydro Pump",
                                                Water,
                                                Special,
                                                110);

            ListOfPokemon[21] = definePokemon("Venusaur",
                                                Grass,
                                                Poison,
                                                80,
                                                80,
                                                82,
                                                83,
                                                100,
                                                100,
                                                80,
                                                "Venusaur_Front.png",
                                                "Venusaur_Back.png",
                                                "Earthquake",
                                                Ground,
                                                Physical,
                                                100,
                                                "Razor Leaf",
                                                Grass,
                                                Physical,
                                                55,
                                                "Sludge Bomb",
                                                Poison,
                                                Special,
                                                90,
                                                "Frenzy Plant",
                                                Grass,
                                                Special,
                                                150);

            ListOfPokemon[22] = definePokemon("Exeggutor",
                                                Grass,
                                                Psychic,
                                                95,
                                                95,
                                                95,
                                                85,
                                                125,
                                                75,
                                                55,
                                                "Exeggutor_Front.png",
                                                "Exeggutor_Back.png",
                                                "Egg Bomb",
                                                Normal,
                                                Physical,
                                                100,
                                                "Psychic",
                                                Psychic,
                                                Special,
                                                90,
                                                "Hyper Beam",
                                                Normal,
                                                Special,
                                                150,
                                                "Ancient Power",
                                                Rock,
                                                Special,
                                                60);

            ListOfPokemon[23] = definePokemon("Vileplume",
                                                Grass,
                                                Poison,
                                                75,
                                                75,
                                                80,
                                                85,
                                                110,
                                                90,
                                                50,
                                                "Vileplume_Front.png",
                                                "Vileplume_Back.png",
                                                "Acid",
                                                Poison,
                                                Special,
                                                40,
                                                "Sludge Bomb",
                                                Poison,
                                                Special,
                                                90,
                                                "Secret Power",
                                                Normal,
                                                Physical,
                                                70,
                                                "Vine Whip",
                                                Grass,
                                                Physical,
                                                45);

            ListOfPokemon[24] = definePokemon("Alakazam",
                                                Psychic,
                                                None,
                                                55,
                                                55,
                                                50,
                                                45,
                                                135,
                                                95,
                                                120,
                                                "Alakazam_Front.png",
                                                "Alakazam_Back.png",
                                                "Psychic",
                                                Psychic,
                                                Special,
                                                90,
                                                "Shadow Ball",
                                                Ghost,
                                                Special,
                                                80,
                                                "Psybeam",
                                                Psychic,
                                                Special,
                                                65,
                                                "Thunder Punch",
                                                Electric,
                                                Physical,
                                                75);

            ListOfPokemon[25] = definePokemon("Mewtwo",
                                                Psychic,
                                                None,
                                                106,
                                                106,
                                                110,
                                                90,
                                                154,
                                                90,
                                                130,
                                                "Mewtwo_Front.png",
                                                "Mewtwo_Back.png",
                                                "Swift",
                                                Normal,
                                                Special,
                                                60,
                                                "Psychic",
                                                Psychic,
                                                Special,
                                                90,
                                                "Shadow Ball",
                                                Ghost,
                                                Special,
                                                80,
                                                "Flamethrower",
                                                Fire,
                                                Special,
                                                90);

            ListOfPokemon[26] = definePokemon("Jynx",
                                                Psychic,
                                                None,
                                                65,
                                                65,
                                                50,
                                                35,
                                                115,
                                                95,
                                                95,
                                                "Jynx_Front.png",
                                                "Jynx_Back.png",
                                                "Psychic",
                                                Psychic,
                                                Special,
                                                90,
                                                "Blizzard",
                                                Ice,
                                                Special,
                                                110,
                                                "Ice Punch",
                                                Ice,
                                                Physical,
                                                75,
                                                "Shadow Ball",
                                                Ghost,
                                                Special,
                                                80);

            ListOfPokemon[27] = definePokemon("Pikachu",
                                                Electric,
                                                None,
                                                35,
                                                35,
                                                55,
                                                40,
                                                50,
                                                50,
                                                90,
                                                "Pikachu_Front.png",
                                                "Pikachu_Back.png",
                                                "Volt Tackle",
                                                Electric,
                                                Physical,
                                                120,
                                                "Iron Tail",
                                                Steel,
                                                Physical,
                                                100,
                                                "Thunderbolt",
                                                Electric,
                                                Special,
                                                90,
                                                "Thunder",
                                                Electric,
                                                Special,
                                                110);

            ListOfPokemon[28] = definePokemon("Jolteon",
                                                Electric,
                                                None,
                                                65,
                                                65,
                                                65,
                                                60,
                                                110,
                                                95,
                                                130,
                                                "Jolteon_Front.png",
                                                "Jolteon_Back.png",
                                                "Iron Tail",
                                                Steel,
                                                Physical,
                                                100,
                                                "Quick Attack",
                                                Normal,
                                                Special,
                                                40,
                                                "Thunderbolt",
                                                Electric,
                                                Special,
                                                90,
                                                "Charge Beam",
                                                Electric,
                                                Special,
                                                50);

            ListOfPokemon[29] = definePokemon("Electabuzz",
                                                Electric,
                                                None,
                                                65,
                                                65,
                                                83,
                                                57,
                                                95,
                                                85,
                                                105,
                                                "Electabuzz_Front.png",
                                                "Electabuzz_Back.png",
                                                "Thunderbolt",
                                                Electric,
                                                Special,
                                                90,
                                                "Thunder",
                                                Electric,
                                                110,
                                                "Quick Attack",
                                                Normal,
                                                Special,
                                                40,
                                                "Swift",
                                                Normal,
                                                Special,
                                                60);
            return ListOfPokemon[];
            }
